// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOaVYXNYAsSB2TrR6huLCcfoqUoJiMYL0',
    appId: '1:38607481539:web:a4d5f23fc5ad8f4e5cd076',
    messagingSenderId: '38607481539',
    projectId: 'sungrak-bible',
    authDomain: 'sungrak-bible.firebaseapp.com',
    databaseURL: 'https://sungrak-bible.firebaseio.com',
    storageBucket: 'sungrak-bible.appspot.com',
    measurementId: 'G-17ZPL9S8ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQr6D6QMJNkLqbE5PuiIRUiRzs-wAKu0',
    appId: '1:38607481539:android:716686274f9075875cd076',
    messagingSenderId: '38607481539',
    projectId: 'sungrak-bible',
    databaseURL: 'https://sungrak-bible.firebaseio.com',
    storageBucket: 'sungrak-bible.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQRBMTGLwIrLvK0bhj-s-vP91Mg3XNbE',
    appId: '1:38607481539:ios:7ebeafe37b743ce25cd076',
    messagingSenderId: '38607481539',
    projectId: 'sungrak-bible',
    databaseURL: 'https://sungrak-bible.firebaseio.com',
    storageBucket: 'sungrak-bible.appspot.com',
    iosClientId: '38607481539-7o8d5dadfohttu803fsbv1sboddmmgv1.apps.googleusercontent.com',
    iosBundleId: 'kr.or.sungrak.cba.srBible',
  );
}
